// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNGaDxqddh48HHBB_jbBtqyv0adGtxTdc',
    appId: '1:326975062200:web:d8289652d77d96ba01f44d',
    messagingSenderId: '326975062200',
    projectId: 'oedu-b60e9',
    authDomain: 'oedu-b60e9.firebaseapp.com',
    storageBucket: 'oedu-b60e9.appspot.com',
    measurementId: 'G-6YTNR4YLTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWswdFAnx9pu7BBr3zfyKxSyFdy2uveHU',
    appId: '1:326975062200:android:806375448ecefd3d01f44d',
    messagingSenderId: '326975062200',
    projectId: 'oedu-b60e9',
    storageBucket: 'oedu-b60e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo2MgNeaa-twAzDnLYxZfHpHlnoBLxiGY',
    appId: '1:326975062200:ios:e327decad33f42d501f44d',
    messagingSenderId: '326975062200',
    projectId: 'oedu-b60e9',
    storageBucket: 'oedu-b60e9.appspot.com',
    iosBundleId: 'com.example.oedu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo2MgNeaa-twAzDnLYxZfHpHlnoBLxiGY',
    appId: '1:326975062200:ios:ae2cc53188bbbd9c01f44d',
    messagingSenderId: '326975062200',
    projectId: 'oedu-b60e9',
    storageBucket: 'oedu-b60e9.appspot.com',
    iosBundleId: 'com.example.oedu.RunnerTests',
  );
}
